"""layer0_1_reference

Revision ID: 0001
Revises: 
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('short_name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('route_id', name=op.f('pk_routes')),
    sa.UniqueConstraint('name', name=op.f('uq_routes_name'))
    )
    op.create_table('schedule_templates',
    sa.Column('schedule_template_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('day_type', sa.Enum('weekday', 'saturday', 'sunday_holiday', name='day_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=False),
    sa.Column('data_status', sa.Enum('draft', 'available', 'missing', name='data_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('schedule_template_id', name=op.f('pk_schedule_templates')),
    sa.UniqueConstraint('name', name=op.f('uq_schedule_templates_name'))
    )
    op.create_table('stops',
    sa.Column('stop_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('geofence_radius_m', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.Enum('verified', 'needs_interpretation', 'unverified', name='verification_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.PrimaryKeyConstraint('stop_id', name=op.f('pk_stops')),
    sa.UniqueConstraint('name', name=op.f('uq_stops_name'))
    )
    op.create_table('route_patterns',
    sa.Column('route_pattern_id', sa.Uuid(), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('pattern_code', sa.Text(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('verification_status', sa.Enum('verified', 'needs_interpretation', 'unverified', name='verification_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], name=op.f('fk_route_patterns_route_id_routes')),
    sa.PrimaryKeyConstraint('route_pattern_id', name=op.f('pk_route_patterns')),
    sa.UniqueConstraint('route_id', 'pattern_code', name=op.f('uq_route_patterns_route_id_pattern_code'))
    )
    op.create_table('schedule_annotations',
    sa.Column('annotation_id', sa.Uuid(), nullable=False),
    sa.Column('source_page', sa.Text(), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('trip_no', sa.Integer(), nullable=True),
    sa.Column('covered_stop_ids', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('min_seconds', sa.Integer(), nullable=True),
    sa.Column('max_seconds', sa.Integer(), nullable=True),
    sa.Column('reference_stop_id', sa.Uuid(), nullable=True),
    sa.Column('verification_status', sa.Enum('verified', 'needs_interpretation', 'unverified', name='verification_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.ForeignKeyConstraint(['reference_stop_id'], ['stops.stop_id'], name=op.f('fk_schedule_annotations_reference_stop_id_stops')),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], name=op.f('fk_schedule_annotations_route_id_routes')),
    sa.PrimaryKeyConstraint('annotation_id', name=op.f('pk_schedule_annotations'))
    )
    op.create_table('source_stop_labels',
    sa.Column('source_reference', sa.Text(), nullable=False),
    sa.Column('raw_name', sa.Text(), nullable=False),
    sa.Column('provisional_stop_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_stop_id', sa.Uuid(), nullable=True),
    sa.Column('verification_status', sa.Enum('verified', 'needs_interpretation', 'unverified', name='verification_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['provisional_stop_id'], ['stops.stop_id'], name=op.f('fk_source_stop_labels_provisional_stop_id_stops')),
    sa.ForeignKeyConstraint(['resolved_stop_id'], ['stops.stop_id'], name=op.f('fk_source_stop_labels_resolved_stop_id_stops')),
    sa.PrimaryKeyConstraint('source_reference', 'raw_name', name=op.f('pk_source_stop_labels'))
    )
    op.create_table('route_versions',
    sa.Column('route_version_id', sa.Uuid(), nullable=False),
    sa.Column('route_pattern_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['route_pattern_id'], ['route_patterns.route_pattern_id'], name=op.f('fk_route_versions_route_pattern_id_route_patterns')),
    sa.PrimaryKeyConstraint('route_version_id', name=op.f('pk_route_versions')),
    sa.UniqueConstraint('route_pattern_id', 'version_no', name=op.f('uq_route_versions_route_pattern_id_version_no'))
    )
    op.create_table('route_path_points',
    sa.Column('route_version_id', sa.Uuid(), nullable=False),
    sa.Column('path_seq', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('path_source', sa.Enum('recorded_track', 'operator_provided', 'manual_trace', name='path_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['route_version_id'], ['route_versions.route_version_id'], name=op.f('fk_route_path_points_route_version_id_route_versions')),
    sa.PrimaryKeyConstraint('route_version_id', 'path_seq', name=op.f('pk_route_path_points'))
    )
    op.create_table('route_stops',
    sa.Column('route_stop_id', sa.Uuid(), nullable=False),
    sa.Column('route_version_id', sa.Uuid(), nullable=False),
    sa.Column('stop_id', sa.Uuid(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('is_origin', sa.Boolean(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('boarding_policy', sa.Enum('allowed', 'not_allowed', 'unknown', name='boarding_policy', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('alighting_policy', sa.Enum('allowed', 'not_allowed', 'unknown', name='alighting_policy', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['route_version_id'], ['route_versions.route_version_id'], name=op.f('fk_route_stops_route_version_id_route_versions')),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.stop_id'], name=op.f('fk_route_stops_stop_id_stops')),
    sa.PrimaryKeyConstraint('route_stop_id', name=op.f('pk_route_stops')),
    sa.UniqueConstraint('route_version_id', 'stop_sequence', name=op.f('uq_route_stops_route_version_id_stop_sequence'))
    )
    op.create_table('survey_tracks',
    sa.Column('survey_track_id', sa.Uuid(), nullable=False),
    sa.Column('route_version_id', sa.Uuid(), nullable=True),
    sa.Column('recorded_on', sa.Date(), nullable=True),
    sa.Column('device_label', sa.Text(), nullable=True),
    sa.Column('gpx_version', sa.Text(), nullable=True),
    sa.Column('point_count', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source_file_hash', sa.Text(), nullable=False),
    sa.Column('source_file_ref', sa.Text(), nullable=True),
    sa.Column('app_version', sa.Text(), nullable=True),
    sa.Column('export_format', sa.Text(), nullable=True),
    sa.Column('recording_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['route_version_id'], ['route_versions.route_version_id'], name=op.f('fk_survey_tracks_route_version_id_route_versions')),
    sa.PrimaryKeyConstraint('survey_track_id', name=op.f('pk_survey_tracks')),
    sa.UniqueConstraint('source_file_hash', name=op.f('uq_survey_tracks_source_file_hash'))
    )
    op.create_table('route_stop_segments',
    sa.Column('route_version_id', sa.Uuid(), nullable=False),
    sa.Column('from_route_stop_id', sa.Uuid(), nullable=False),
    sa.Column('to_route_stop_id', sa.Uuid(), nullable=False),
    sa.Column('path_from_seq', sa.Integer(), nullable=False),
    sa.Column('path_to_seq', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Double(), nullable=True),
    sa.Column('path_source', sa.Enum('recorded_track', 'operator_provided', 'manual_trace', name='path_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('verification_status', sa.Enum('verified', 'needs_interpretation', 'unverified', name='verification_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.ForeignKeyConstraint(['from_route_stop_id'], ['route_stops.route_stop_id'], name=op.f('fk_route_stop_segments_from_route_stop_id_route_stops')),
    sa.ForeignKeyConstraint(['route_version_id', 'path_from_seq'], ['route_path_points.route_version_id', 'route_path_points.path_seq'], name=op.f('fk_route_stop_segments_route_version_id_path_from_seq_route_path_points')),
    sa.ForeignKeyConstraint(['route_version_id', 'path_to_seq'], ['route_path_points.route_version_id', 'route_path_points.path_seq'], name=op.f('fk_route_stop_segments_route_version_id_path_to_seq_route_path_points')),
    sa.ForeignKeyConstraint(['route_version_id'], ['route_versions.route_version_id'], name=op.f('fk_route_stop_segments_route_version_id_route_versions')),
    sa.ForeignKeyConstraint(['to_route_stop_id'], ['route_stops.route_stop_id'], name=op.f('fk_route_stop_segments_to_route_stop_id_route_stops')),
    sa.PrimaryKeyConstraint('route_version_id', 'from_route_stop_id', 'to_route_stop_id', name=op.f('pk_route_stop_segments'))
    )
    op.create_table('survey_track_points',
    sa.Column('survey_track_id', sa.Uuid(), nullable=False),
    sa.Column('point_seq', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('elevation_m', sa.Double(), nullable=True),
    sa.Column('speed_mps', sa.Double(), nullable=True),
    sa.Column('bearing_deg', sa.Double(), nullable=True),
    sa.Column('sat_count', sa.Integer(), nullable=True),
    sa.Column('hdop', sa.Double(), nullable=True),
    sa.Column('accuracy_m', sa.Double(), nullable=True),
    sa.Column('raw_extensions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['survey_track_id'], ['survey_tracks.survey_track_id'], name=op.f('fk_survey_track_points_survey_track_id_survey_tracks')),
    sa.PrimaryKeyConstraint('survey_track_id', 'point_seq', name=op.f('pk_survey_track_points'))
    )
    op.create_table('trip_templates',
    sa.Column('trip_template_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_template_id', sa.Uuid(), nullable=False),
    sa.Column('route_version_id', sa.Uuid(), nullable=False),
    sa.Column('trip_no', sa.Integer(), nullable=False),
    sa.Column('source_row_key', sa.Text(), nullable=False),
    sa.Column('origin_route_stop_id', sa.Uuid(), nullable=True),
    sa.Column('excluded_weekdays', sa.ARRAY(sa.String(length=3)), nullable=False),
    sa.Column('vehicle_count_by_weekday', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schedule_source', sa.Enum('school_pdf', 'operator_entry', 'unknown', name='schedule_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('punctuality_assumption', sa.Enum('user_asserted_on_time', 'not_assumed', name='punctuality_assumption', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('source_cells', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['origin_route_stop_id'], ['route_stops.route_stop_id'], name=op.f('fk_trip_templates_origin_route_stop_id_route_stops')),
    sa.ForeignKeyConstraint(['route_version_id'], ['route_versions.route_version_id'], name=op.f('fk_trip_templates_route_version_id_route_versions')),
    sa.ForeignKeyConstraint(['schedule_template_id'], ['schedule_templates.schedule_template_id'], name=op.f('fk_trip_templates_schedule_template_id_schedule_templates')),
    sa.PrimaryKeyConstraint('trip_template_id', name=op.f('pk_trip_templates')),
    sa.UniqueConstraint('source_row_key', name=op.f('uq_trip_templates_source_row_key'))
    )
    op.create_table('scheduled_stop_times',
    sa.Column('trip_template_id', sa.Uuid(), nullable=False),
    sa.Column('route_stop_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('arrival', 'departure', 'unspecified', name='event_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('day_offset', sa.Integer(), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('schedule_source', sa.Enum('school_pdf', 'operator_entry', 'unknown', name='schedule_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.ForeignKeyConstraint(['route_stop_id'], ['route_stops.route_stop_id'], name=op.f('fk_scheduled_stop_times_route_stop_id_route_stops')),
    sa.ForeignKeyConstraint(['trip_template_id'], ['trip_templates.trip_template_id'], name=op.f('fk_scheduled_stop_times_trip_template_id_trip_templates')),
    sa.PrimaryKeyConstraint('trip_template_id', 'route_stop_id', 'event_type', name=op.f('pk_scheduled_stop_times'))
    )
    op.create_table('survey_annotations',
    sa.Column('annotation_id', sa.Uuid(), nullable=False),
    sa.Column('survey_track_id', sa.Uuid(), nullable=False),
    sa.Column('annotation_seq', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('linked_point_seq', sa.Integer(), nullable=True),
    sa.Column('resolved_route_stop_id', sa.Uuid(), nullable=True),
    sa.Column('verification_status', sa.Enum('verified', 'needs_interpretation', 'unverified', name='verification_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.ForeignKeyConstraint(['resolved_route_stop_id'], ['route_stops.route_stop_id'], name=op.f('fk_survey_annotations_resolved_route_stop_id_route_stops')),
    sa.ForeignKeyConstraint(['survey_track_id', 'linked_point_seq'], ['survey_track_points.survey_track_id', 'survey_track_points.point_seq'], name=op.f('fk_survey_annotations_survey_track_id_linked_point_seq_survey_track_points')),
    sa.ForeignKeyConstraint(['survey_track_id'], ['survey_tracks.survey_track_id'], name=op.f('fk_survey_annotations_survey_track_id_survey_tracks')),
    sa.PrimaryKeyConstraint('annotation_id', name=op.f('pk_survey_annotations')),
    sa.UniqueConstraint('survey_track_id', 'annotation_seq', name=op.f('uq_survey_annotations_survey_track_id_annotation_seq'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_annotations')
    op.drop_table('scheduled_stop_times')
    op.drop_table('trip_templates')
    op.drop_table('survey_track_points')
    op.drop_table('route_stop_segments')
    op.drop_table('survey_tracks')
    op.drop_table('route_stops')
    op.drop_table('route_path_points')
    op.drop_table('route_versions')
    op.drop_table('source_stop_labels')
    op.drop_table('schedule_annotations')
    op.drop_table('route_patterns')
    op.drop_table('stops')
    op.drop_table('schedule_templates')
    op.drop_table('routes')
    # ### end Alembic commands ###
