"""layer2_service_calendar

Revision ID: 0002
Revises: 0001
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_exceptions',
    sa.Column('exception_id', sa.Uuid(), nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=True),
    sa.Column('exception_type', sa.Enum('no_service', 'alternate_schedule', name='exception_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('alternate_schedule_template_id', sa.Uuid(), nullable=True),
    sa.Column('source_reference', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("(exception_type = 'alternate_schedule') = (alternate_schedule_template_id IS NOT NULL)", name=op.f('ck_schedule_exceptions_alternate_template')),
    sa.ForeignKeyConstraint(['alternate_schedule_template_id'], ['schedule_templates.schedule_template_id'], name=op.f('fk_schedule_exceptions_alternate_schedule_template_id_schedule_templates')),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], name=op.f('fk_schedule_exceptions_route_id_routes')),
    sa.PrimaryKeyConstraint('exception_id', name=op.f('pk_schedule_exceptions')),
    sa.UniqueConstraint('exception_date', 'route_id', name=op.f('uq_schedule_exceptions_exception_date_route_id'), postgresql_nulls_not_distinct=True)
    )
    op.create_table('schedule_route_coverage',
    sa.Column('schedule_template_id', sa.Uuid(), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('coverage_status', sa.Enum('confirmed_service', 'confirmed_no_service', 'unknown', name='coverage_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_trip_count', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], name=op.f('fk_schedule_route_coverage_route_id_routes')),
    sa.ForeignKeyConstraint(['schedule_template_id'], ['schedule_templates.schedule_template_id'], name=op.f('fk_schedule_route_coverage_schedule_template_id_schedule_templates')),
    sa.PrimaryKeyConstraint('schedule_template_id', 'route_id', name=op.f('pk_schedule_route_coverage'))
    )
    op.create_table('service_calendar',
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_status', sa.Enum('available', 'no_service', 'unknown', 'out_of_period', name='schedule_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('applied_schedule_template_id', sa.Uuid(), nullable=True),
    sa.Column('actual_weekday', sa.String(length=3), nullable=False),
    sa.Column('effective_service_weekday', sa.String(length=3), nullable=True),
    sa.Column('effective_day_type', sa.Enum('weekday', 'saturday', 'sunday_holiday', name='effective_day_type', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applied_schedule_template_id'], ['schedule_templates.schedule_template_id'], name=op.f('fk_service_calendar_applied_schedule_template_id_schedule_templates')),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], name=op.f('fk_service_calendar_route_id_routes')),
    sa.PrimaryKeyConstraint('service_date', 'route_id', name=op.f('pk_service_calendar'))
    )
    op.create_table('scheduled_trips',
    sa.Column('scheduled_trip_id', sa.Uuid(), nullable=False),
    sa.Column('trip_template_id', sa.Uuid(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('route_version_id', sa.Uuid(), nullable=False),
    sa.Column('origin_trip_stop_id', sa.Uuid(), nullable=True),
    sa.Column('operation_status', sa.Enum('scheduled', 'scheduled_running', 'completed', 'cancelled', name='operation_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('scheduled_vehicle_count', sa.Integer(), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('control_version', sa.Integer(), nullable=False),
    sa.Column('source_row_key', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['route_version_id'], ['route_versions.route_version_id'], name=op.f('fk_scheduled_trips_route_version_id_route_versions')),
    sa.ForeignKeyConstraint(['trip_template_id'], ['trip_templates.trip_template_id'], name=op.f('fk_scheduled_trips_trip_template_id_trip_templates')),
    sa.PrimaryKeyConstraint('scheduled_trip_id', name=op.f('pk_scheduled_trips')),
    sa.UniqueConstraint('source_row_key', 'service_date', name=op.f('uq_scheduled_trips_source_row_key_service_date')),
    sa.UniqueConstraint('trip_template_id', 'service_date', name=op.f('uq_scheduled_trips_trip_template_id_service_date'))
    )
    op.create_table('scheduled_trip_stops',
    sa.Column('trip_stop_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_trip_id', sa.Uuid(), nullable=False),
    sa.Column('route_stop_id', sa.Uuid(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('scheduled_arrival_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_departure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_unspecified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('boarding_policy', sa.Enum('allowed', 'not_allowed', 'unknown', name='boarding_policy', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('alighting_policy', sa.Enum('allowed', 'not_allowed', 'unknown', name='alighting_policy', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('verification_status', sa.Enum('verified', 'needs_interpretation', 'unverified', name='verification_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.ForeignKeyConstraint(['route_stop_id'], ['route_stops.route_stop_id'], name=op.f('fk_scheduled_trip_stops_route_stop_id_route_stops')),
    sa.ForeignKeyConstraint(['scheduled_trip_id'], ['scheduled_trips.scheduled_trip_id'], name=op.f('fk_scheduled_trip_stops_scheduled_trip_id_scheduled_trips')),
    sa.PrimaryKeyConstraint('trip_stop_id', name=op.f('pk_scheduled_trip_stops')),
    sa.UniqueConstraint('scheduled_trip_id', 'route_stop_id', name=op.f('uq_scheduled_trip_stops_scheduled_trip_id_route_stop_id')),
    sa.UniqueConstraint('scheduled_trip_id', 'stop_sequence', name=op.f('uq_scheduled_trip_stops_scheduled_trip_id_stop_sequence'))
    )
    op.create_table('trip_vehicles',
    sa.Column('trip_vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_trip_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_slot', sa.Integer(), nullable=False),
    sa.Column('shuttle_id', sa.Uuid(), nullable=True),
    sa.Column('operation_status', sa.Enum('scheduled', 'scheduled_running', 'completed', 'cancelled', name='operation_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('information_status', sa.Enum('timetable_only', 'observed', 'stale', 'unavailable', name='information_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('departure_observation_event_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['scheduled_trip_id'], ['scheduled_trips.scheduled_trip_id'], name=op.f('fk_trip_vehicles_scheduled_trip_id_scheduled_trips')),
    sa.PrimaryKeyConstraint('trip_vehicle_id', name=op.f('pk_trip_vehicles')),
    sa.UniqueConstraint('scheduled_trip_id', 'vehicle_slot', name=op.f('uq_trip_vehicles_scheduled_trip_id_vehicle_slot'))
    )
    # 회차↔기점 방문 순환 참조. autogenerate가 use_alter FK를 빠뜨려 직접 건다
    op.create_foreign_key(
        op.f('fk_scheduled_trips_origin_trip_stop_id_scheduled_trip_stops'),
        'scheduled_trips', 'scheduled_trip_stops',
        ['origin_trip_stop_id'], ['trip_stop_id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('fk_scheduled_trips_origin_trip_stop_id_scheduled_trip_stops'), 'scheduled_trips', type_='foreignkey'
    )
    op.drop_table('trip_vehicles')
    op.drop_table('scheduled_trip_stops')
    op.drop_table('scheduled_trips')
    op.drop_table('service_calendar')
    op.drop_table('schedule_route_coverage')
    op.drop_table('schedule_exceptions')
    # ### end Alembic commands ###
