"""layer3_observation_staff_idempotency

Revision ID: 0003
Revises: 0002
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('request_hash', sa.Text(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('account_id', 'idempotency_key', name=op.f('pk_idempotency_records'))
    )
    op.create_table('staff_accounts',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('collector', 'admin', name='role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('account_id', name=op.f('pk_staff_accounts')),
    sa.UniqueConstraint('username', name=op.f('uq_staff_accounts_username'))
    )
    op.create_table('collection_sessions',
    sa.Column('collection_session_id', sa.Uuid(), nullable=False),
    sa.Column('trip_vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('shuttle_id', sa.Uuid(), nullable=True),
    sa.Column('collector_id', sa.Uuid(), nullable=True),
    sa.Column('producer_type', sa.Enum('manual', 'gps', name='producer_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('comparison_policy', sa.Enum('manual_only', 'manual_reference', 'gps_primary', name='comparison_policy', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('collection_start_trip_stop_id', sa.Uuid(), nullable=True),
    sa.Column('collection_status', sa.Enum('not_started', 'collecting', 'ended', 'needs_review', name='collection_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('input_version', sa.Integer(), nullable=False),
    sa.Column('writer_instance_id', sa.Uuid(), nullable=True),
    sa.Column('end_reason', sa.Enum('reassigned', 'terminal_departed', 'signal_lost', 'service_day_closed', name='end_reason', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(collection_status = 'ended') = (ended_at IS NOT NULL)", name=op.f('ck_collection_sessions_ended_matches_status')),
    sa.ForeignKeyConstraint(['collection_start_trip_stop_id'], ['scheduled_trip_stops.trip_stop_id'], name=op.f('fk_collection_sessions_collection_start_trip_stop_id_scheduled_trip_stops')),
    sa.ForeignKeyConstraint(['collector_id'], ['staff_accounts.account_id'], name=op.f('fk_collection_sessions_collector_id_staff_accounts')),
    sa.ForeignKeyConstraint(['trip_vehicle_id'], ['trip_vehicles.trip_vehicle_id'], name=op.f('fk_collection_sessions_trip_vehicle_id_trip_vehicles')),
    sa.PrimaryKeyConstraint('collection_session_id', name=op.f('pk_collection_sessions'))
    )
    op.create_index('uq_collection_sessions_open_per_producer', 'collection_sessions', ['trip_vehicle_id', 'producer_type'], unique=True, postgresql_where=sa.text('ended_at IS NULL'))
    op.create_table('clock_checks',
    sa.Column('clock_check_id', sa.Uuid(), nullable=False),
    sa.Column('collection_session_id', sa.Uuid(), nullable=False),
    sa.Column('device_sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_responded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_offset_seconds', sa.Double(), nullable=True),
    sa.Column('uncertainty_seconds', sa.Double(), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_session_id'], ['collection_sessions.collection_session_id'], name=op.f('fk_clock_checks_collection_session_id_collection_sessions')),
    sa.PrimaryKeyConstraint('clock_check_id', name=op.f('pk_clock_checks'))
    )
    op.create_table('location_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('collection_session_id', sa.Uuid(), nullable=False),
    sa.Column('trip_vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('trip_stop_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('arrived', 'departed', 'passed', 'skipped', name='event_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_confidence', sa.Enum('observed', 'interpolated', 'inferred', name='time_confidence', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('manual', 'gps', 'system', name='source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('client_event_id', sa.Text(), nullable=False),
    sa.Column('client_sequence', sa.Integer(), nullable=True),
    sa.Column('clock_check_id', sa.Uuid(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.Enum('valid', 'needs_review', 'cancelled', name='validation_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('parent_event_id', sa.Uuid(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("(occurred_at IS NULL) = (time_confidence = 'inferred')", name=op.f('ck_location_events_inferred_has_no_time')),
    sa.CheckConstraint("(source = 'system') = (client_sequence IS NULL)", name=op.f('ck_location_events_system_has_no_sequence')),
    sa.ForeignKeyConstraint(['clock_check_id'], ['clock_checks.clock_check_id'], name=op.f('fk_location_events_clock_check_id_clock_checks')),
    sa.ForeignKeyConstraint(['collection_session_id'], ['collection_sessions.collection_session_id'], name=op.f('fk_location_events_collection_session_id_collection_sessions')),
    sa.ForeignKeyConstraint(['parent_event_id'], ['location_events.event_id'], name=op.f('fk_location_events_parent_event_id_location_events')),
    sa.ForeignKeyConstraint(['trip_stop_id'], ['scheduled_trip_stops.trip_stop_id'], name=op.f('fk_location_events_trip_stop_id_scheduled_trip_stops')),
    sa.ForeignKeyConstraint(['trip_vehicle_id'], ['trip_vehicles.trip_vehicle_id'], name=op.f('fk_location_events_trip_vehicle_id_trip_vehicles')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_location_events')),
    sa.UniqueConstraint('collection_session_id', 'client_event_id', name=op.f('uq_location_events_collection_session_id_client_event_id'))
    )
    op.create_index('uq_location_events_session_client_sequence', 'location_events', ['collection_session_id', 'client_sequence'], unique=True, postgresql_where=sa.text('client_sequence IS NOT NULL'))
    op.create_index('uq_location_events_valid_visit_event', 'location_events', ['trip_stop_id', 'trip_vehicle_id', 'event_type'], unique=True, postgresql_where=sa.text("validation_status = 'valid'"))
    op.create_table('observation_reviews',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Enum('cancel', 'approve', 'reject', 'restore', name='decision', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('previous_validation_status', sa.Enum('valid', 'needs_review', 'cancelled', name='previous_validation_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_version', sa.Integer(), nullable=True),
    sa.Column('control_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['location_events.event_id'], name=op.f('fk_observation_reviews_event_id_location_events')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['staff_accounts.account_id'], name=op.f('fk_observation_reviews_reviewed_by_staff_accounts')),
    sa.PrimaryKeyConstraint('review_id', name=op.f('pk_observation_reviews'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observation_reviews')
    op.drop_index('uq_location_events_valid_visit_event', table_name='location_events', postgresql_where=sa.text("validation_status = 'valid'"))
    op.drop_index('uq_location_events_session_client_sequence', table_name='location_events', postgresql_where=sa.text('client_sequence IS NOT NULL'))
    op.drop_table('location_events')
    op.drop_table('clock_checks')
    op.drop_index('uq_collection_sessions_open_per_producer', table_name='collection_sessions', postgresql_where=sa.text('ended_at IS NULL'))
    op.drop_table('collection_sessions')
    op.drop_table('staff_accounts')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
