"""layer5_operations_notices_decisions

Revision ID: 0004
Revises: 0003
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notices',
    sa.Column('notice_id', sa.Uuid(), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_trip_id', sa.Uuid(), nullable=True),
    sa.Column('notice_type', sa.Enum('delay', 'cancel', 'info', name='notice_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expired_early_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_notices_expires_after_created')),
    sa.ForeignKeyConstraint(['created_by'], ['staff_accounts.account_id'], name=op.f('fk_notices_created_by_staff_accounts')),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], name=op.f('fk_notices_route_id_routes')),
    sa.ForeignKeyConstraint(['scheduled_trip_id'], ['scheduled_trips.scheduled_trip_id'], name=op.f('fk_notices_scheduled_trip_id_scheduled_trips')),
    sa.PrimaryKeyConstraint('notice_id', name=op.f('pk_notices'))
    )
    op.create_index(op.f('ix_notices_route_id_expires_at'), 'notices', ['route_id', 'expires_at'], unique=False)
    op.create_table('operation_decisions',
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_trip_id', sa.Uuid(), nullable=False),
    sa.Column('trip_vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('decision_type', sa.Enum('complete', 'cancel_trip', 'keep_completed', 'reopen', name='decision_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('evidence_type', sa.Enum('terminal_observation', 'collector_report', 'operator_notice', 'admin_judgement', name='evidence_type', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('evidence_event_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('observed_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supersedes_decision_id', sa.Uuid(), nullable=True),
    sa.Column('control_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("decision_type = 'cancel_trip' OR trip_vehicle_id IS NOT NULL", name=op.f('ck_operation_decisions_vehicle_decision_has_vehicle')),
    sa.CheckConstraint("decision_type NOT IN ('complete', 'keep_completed') OR evidence_type IS NOT NULL", name=op.f('ck_operation_decisions_completion_has_evidence')),
    sa.ForeignKeyConstraint(['decided_by'], ['staff_accounts.account_id'], name=op.f('fk_operation_decisions_decided_by_staff_accounts')),
    sa.ForeignKeyConstraint(['evidence_event_id'], ['location_events.event_id'], name=op.f('fk_operation_decisions_evidence_event_id_location_events')),
    sa.ForeignKeyConstraint(['scheduled_trip_id'], ['scheduled_trips.scheduled_trip_id'], name=op.f('fk_operation_decisions_scheduled_trip_id_scheduled_trips')),
    sa.ForeignKeyConstraint(['supersedes_decision_id'], ['operation_decisions.decision_id'], name=op.f('fk_operation_decisions_supersedes_decision_id_operation_decisions')),
    sa.ForeignKeyConstraint(['trip_vehicle_id'], ['trip_vehicles.trip_vehicle_id'], name=op.f('fk_operation_decisions_trip_vehicle_id_trip_vehicles')),
    sa.PrimaryKeyConstraint('decision_id', name=op.f('pk_operation_decisions'))
    )
    op.create_index(op.f('ix_operation_decisions_scheduled_trip_id_decided_at'), 'operation_decisions', ['scheduled_trip_id', 'decided_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_decisions_scheduled_trip_id_decided_at'), table_name='operation_decisions')
    op.drop_table('operation_decisions')
    op.drop_index(op.f('ix_notices_route_id_expires_at'), table_name='notices')
    op.drop_table('notices')
    # ### end Alembic commands ###
