"""layer5_realtime_snapshots_outbox

Revision ID: 0005
Revises: 0004
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('outbox_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('room', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('outbox_id', name=op.f('pk_outbox_events'))
    )
    op.create_index('ix_outbox_events_pending', 'outbox_events', ['outbox_id'], unique=False, postgresql_where=sa.text('sent_at IS NULL'))
    op.create_table('trip_state_snapshots',
    sa.Column('scheduled_trip_id', sa.Uuid(), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('candidate_signature', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scheduled_trip_id'], ['scheduled_trips.scheduled_trip_id'], name=op.f('fk_trip_state_snapshots_scheduled_trip_id_scheduled_trips')),
    sa.PrimaryKeyConstraint('scheduled_trip_id', name=op.f('pk_trip_state_snapshots'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_state_snapshots')
    op.drop_index('ix_outbox_events_pending', table_name='outbox_events', postgresql_where=sa.text('sent_at IS NULL'))
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
