"""survey_path_builds_provenance

Revision ID: 0008
Revises: 0007
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_path_builds',
    sa.Column('route_version_id', sa.Uuid(), nullable=False),
    sa.Column('survey_track_id', sa.Uuid(), nullable=False),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tolerance_m', sa.Double(), nullable=False),
    sa.Column('point_count', sa.Integer(), nullable=False),
    sa.Column('verified_by_track_id', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verify_max_deviation_m', sa.Double(), nullable=True),
    sa.ForeignKeyConstraint(['route_version_id'], ['route_versions.route_version_id'], name=op.f('fk_survey_path_builds_route_version_id_route_versions')),
    sa.ForeignKeyConstraint(['survey_track_id'], ['survey_tracks.survey_track_id'], name=op.f('fk_survey_path_builds_survey_track_id_survey_tracks')),
    sa.ForeignKeyConstraint(['verified_by_track_id'], ['survey_tracks.survey_track_id'], name=op.f('fk_survey_path_builds_verified_by_track_id_survey_tracks')),
    sa.PrimaryKeyConstraint('route_version_id', name=op.f('pk_survey_path_builds'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_path_builds')
    # ### end Alembic commands ###
