"""P0 완료 판정: FR-DM-01 FK 방향, 마이그레이션 up/down 왕복, 모델과 스키마 일치."""

import psycopg
import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import inspect
from sqlalchemy.engine import make_url

from app.models import LAYERS, Base
from tests.conftest import TEST_DATABASE_URL, alembic_config, reset_schema


def test_every_table_has_a_layer():
    assert set(Base.metadata.tables) == set(LAYERS)


def test_fr_dm_01_no_reference_against_layer_order(engine):
    """아래층이 위층을 참조할 뿐 그 반대는 없다 (15 1장).

    예외 하나: ⓪ 조사 자료는 무엇을 조사했는지 ①의 노선 버전·방문을 가리킬 수 있다.
    """
    insp = inspect(engine)
    violations = []
    for table in insp.get_table_names():
        if table == "alembic_version":
            continue
        for fk in insp.get_foreign_keys(table):
            src_layer, dst_layer = LAYERS[table], LAYERS[fk["referred_table"]]
            survey_link = src_layer == 0 and dst_layer == 1
            if src_layer < dst_layer and not survey_link:
                violations.append(f"{table} → {fk['referred_table']}")
    assert violations == []


def test_origin_trip_stop_fk_exists(engine):
    fks = inspect(engine).get_foreign_keys("scheduled_trips")
    assert any(fk["referred_table"] == "scheduled_trip_stops" for fk in fks)


@pytest.fixture
def scratch_url():
    url = make_url(TEST_DATABASE_URL)
    name = f"{url.database}_migrations"
    admin = url.set(database="postgres", drivername="postgresql").render_as_string(hide_password=False)
    with psycopg.connect(admin, autocommit=True) as conn:
        conn.execute(f'DROP DATABASE IF EXISTS "{name}"')
        conn.execute(f'CREATE DATABASE "{name}"')
    yield url.set(database=name).render_as_string(hide_password=False)
    with psycopg.connect(admin, autocommit=True) as conn:
        conn.execute(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)')


def test_migration_roundtrip_and_models_match(scratch_url):
    cfg = alembic_config(scratch_url)
    reset_schema(scratch_url)
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")
    command.upgrade(cfg, "head")
    try:
        command.check(cfg)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - 실패 메시지용
        pytest.fail(f"모델과 마이그레이션이 다르다: {exc}")
